import type { Metadata, Viewport } from "next"; // 👈 Viewport を追加
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "就活管理アプリ",
  description: "Generated by create next app",
  manifest: "/manifest.json", // 👈 これを追加
};

// ▼▼ これを追加（スマホのバーの色設定） ▼▼
export const viewport: Viewport = {
  themeColor: "#2563eb",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>{children}</body>
    </html>
  );
}